//! Guided first-time setup: generate a MATCHED server + client config pair,
//! cross-wired (keys + shared obfuscation PSK) in one go. Backs `chameleon-pq
//! init`.
//!
//! The classic flow (`keygen` prints one node's keypair, you hand-copy the
//! public keys into the peer's config) assumes two strangers exchanging keys
//! out-of-band. A solo operator who runs BOTH ends would keygen twice and paste
//! four hex blobs between two hand-edited files. `init` collapses that: it makes
//! two fresh identities, wires each side's public keys into the OTHER config,
//! shares one PSK, and writes two complete, secure-by-default configs.

use crate::crypto::{Ed25519Auth, MlDsaAuth};
use crate::error::{ChameleonError, Result};
use rand::RngCore;
use std::net::SocketAddr;
use zeroize::Zeroize;

/// The choices that shape a generated config pair.
pub struct PairParams {
    /// Address the CLIENT connects to — the server's reachable `ip:port`.
    pub server_addr: SocketAddr,
    /// Address the SERVER binds.
    pub bind_addr: SocketAddr,
    /// TUN `/24` network base, e.g. `[10, 99, 0]` → server `.1`, client `.2`.
    pub tun_net: [u8; 3],
    /// TUN MTU (validated ≤ 1232 for the obfuscated path).
    pub mtu: u16,
    /// Client routes ALL traffic through the tunnel (full-tunnel VPN).
    pub full_tunnel: bool,
    /// Enable the client kill switch (only meaningful with `full_tunnel`).
    pub kill_switch: bool,
    /// Traffic profile keyword written into both configs (`off`/`balanced`/…).
    pub profile: String,
}

/// One node's fresh identity as hex strings.
struct KeyMat {
    ed_seed: String,
    ed_pub: String,
    mldsa_sk: String,
    mldsa_pub: String,
}

/// Generate a matched server + client config pair. Returns `(server_toml,
/// client_toml)` — two complete configs, cross-wired so each trusts the other.
pub fn init_pair(params: &PairParams) -> (String, String) {
    let server = gen_node();
    let client = gen_node();
    let psk = gen_psk_hex();
    build_pair(params, &server, &client, &psk)
}

/// Parse a `/24` network base like `"10.99.0"` into its three octets.
pub fn parse_tun_net(s: &str) -> Result<[u8; 3]> {
    let parts: Vec<&str> = s.split('.').collect();
    let octets: Option<Vec<u8>> = parts.iter().map(|p| p.parse::<u8>().ok()).collect();
    match octets {
        Some(o) if o.len() == 3 => Ok([o[0], o[1], o[2]]),
        _ => Err(ChameleonError::Handshake {
            state: "init".into(),
            msg: format!("--tun-net '{s}' must be a /24 base like 10.99.0"),
        }),
    }
}

fn gen_node() -> KeyMat {
    let mut seed = [0u8; 32];
    rand::rngs::OsRng.fill_bytes(&mut seed);
    let ed_pub = Ed25519Auth::derive_public(&seed);
    let (mldsa_pub, mldsa_sk) = MlDsaAuth::generate();
    let km = KeyMat {
        ed_seed: hex(&seed),
        ed_pub: hex(&ed_pub),
        mldsa_sk: hex(&mldsa_sk),
        mldsa_pub: hex(&mldsa_pub),
    };
    seed.zeroize(); // the seed now lives only in the hex string / config file
    km
}

/// 32 random bytes as hex — the shared handshake-obfuscation secret.
fn gen_psk_hex() -> String {
    let mut psk = [0u8; 32];
    rand::rngs::OsRng.fill_bytes(&mut psk);
    let s = hex(&psk);
    psk.zeroize();
    s
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

/// Format the two configs. Pure (no I/O, no RNG) so it is unit-testable: given
/// the same keys and params it always yields the same, valid TOML.
fn build_pair(p: &PairParams, server: &KeyMat, client: &KeyMat, psk: &str) -> (String, String) {
    let [a, b, c] = p.tun_net;
    let server_tun = format!("{a}.{b}.{c}.1"); // server = .1 (the tunnel gateway)
    let client_tun = format!("{a}.{b}.{c}.2"); // client = .2
    let mtu = p.mtu;
    let profile = &p.profile;

    // SERVER: trusts the CLIENT's public keys; binds and forwards.
    let server_toml = format!(
        "# Chameleon-PQ SERVER config — generated by `chameleon-pq init`.\n\
         # SECRET: holds this node's private keys. Do not share or commit.\n\
         \n\
         [identity]\n\
         ed25519_seed_hex     = \"{s_seed}\"\n\
         mldsa_secret_hex     = \"{s_sk}\"\n\
         peer_ed25519_pub_hex = \"{c_pub}\"\n\
         peer_mldsa_pub_hex   = \"{c_mldsa}\"\n\
         \n\
         [network]\n\
         bind_addr = \"{bind}\"\n\
         \n\
         [tun]\n\
         name    = \"chameleon0\"\n\
         address = \"{server_tun}\"\n\
         netmask = \"255.255.255.0\"\n\
         mtu     = {mtu}\n\
         \n\
         [obfuscation]\n\
         enabled   = true\n\
         handshake = true\n\
         psk_hex   = \"{psk}\"\n\
         \n\
         [traffic]\n\
         profile = \"{profile}\"\n",
        s_seed = server.ed_seed,
        s_sk = server.mldsa_sk,
        c_pub = client.ed_pub,
        c_mldsa = client.mldsa_pub,
        bind = p.bind_addr,
    );

    // CLIENT: trusts the SERVER's public keys; connects (and, for a full tunnel,
    // routes everything through the server at .1).
    let mut client_tun_block = format!(
        "[tun]\n\
         name         = \"chameleon0\"\n\
         address      = \"{client_tun}\"\n\
         netmask      = \"255.255.255.0\"\n\
         mtu          = {mtu}\n\
         route_all    = {full_tunnel}\n\
         peer_address = \"{server_tun}\"\n",
        full_tunnel = p.full_tunnel,
    );
    if p.full_tunnel {
        client_tun_block.push_str(&format!("kill_switch  = {}\n", p.kill_switch));
    }

    let client_toml = format!(
        "# Chameleon-PQ CLIENT config — generated by `chameleon-pq init`.\n\
         # SECRET: holds this node's private keys. Do not share or commit.\n\
         \n\
         [identity]\n\
         ed25519_seed_hex     = \"{c_seed}\"\n\
         mldsa_secret_hex     = \"{c_sk}\"\n\
         peer_ed25519_pub_hex = \"{s_pub}\"\n\
         peer_mldsa_pub_hex   = \"{s_mldsa}\"\n\
         \n\
         [network]\n\
         server_addr = \"{server_addr}\"\n\
         \n\
         {client_tun_block}\n\
         [obfuscation]\n\
         enabled   = true\n\
         handshake = true\n\
         psk_hex   = \"{psk}\"\n\
         \n\
         [traffic]\n\
         profile = \"{profile}\"\n",
        c_seed = client.ed_seed,
        c_sk = client.mldsa_sk,
        s_pub = server.ed_pub,
        s_mldsa = server.mldsa_pub,
        server_addr = p.server_addr,
    );

    (server_toml, client_toml)
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::config::AppConfig;

    fn params() -> PairParams {
        PairParams {
            server_addr: "203.0.113.5:51820".parse().unwrap(),
            bind_addr: "0.0.0.0:51820".parse().unwrap(),
            tun_net: [10, 99, 0],
            mtu: 1200,
            full_tunnel: true,
            kill_switch: true,
            profile: "off".into(),
        }
    }

    #[test]
    fn generated_pair_is_valid_and_cross_wired() {
        let (server_toml, client_toml) = init_pair(&params());
        // Both must parse AND pass the full config validation.
        let s = AppConfig::from_toml_str(&server_toml).expect("server config invalid");
        let c = AppConfig::from_toml_str(&client_toml).expect("client config invalid");

        // Cross-wiring: each side's peer keys are the OTHER side's own public keys.
        let s_own_pub = hex(&Ed25519Auth::derive_public(
            &s.identity.seed_bytes().unwrap()[..],
        ));
        let c_own_pub = hex(&Ed25519Auth::derive_public(
            &c.identity.seed_bytes().unwrap()[..],
        ));
        assert_eq!(c.identity.peer_ed25519_pub_hex, s_own_pub);
        assert_eq!(s.identity.peer_ed25519_pub_hex, c_own_pub);

        // Both hybrid (ML-DSA set on both sides) and sharing one PSK.
        assert!(s.identity.has_mldsa() && c.identity.has_mldsa());
        assert_eq!(s.obfuscation.psk_hex, c.obfuscation.psk_hex);
        assert!(s.obfuscation.psk_hex.is_some());

        // Topology: client is full-tunnel, gateway = server's tun address.
        assert!(c.tun.route_all);
        assert_eq!(c.tun.peer_address.as_deref(), Some("10.99.0.1"));
        assert_eq!(c.tun.address, "10.99.0.2");
        assert_eq!(s.tun.address, "10.99.0.1");
        assert_eq!(
            c.network.server_addr.unwrap().to_string(),
            "203.0.113.5:51820"
        );
    }

    #[test]
    fn split_tunnel_omits_kill_switch() {
        let mut p = params();
        p.full_tunnel = false;
        p.kill_switch = false;
        let (_s, client_toml) = init_pair(&p);
        let c = AppConfig::from_toml_str(&client_toml).unwrap();
        assert!(!c.tun.route_all);
        assert!(!c.tun.kill_switch);
    }

    #[test]
    fn two_calls_generate_distinct_keys() {
        let (s1, _) = init_pair(&params());
        let (s2, _) = init_pair(&params());
        // Fresh randomness each run → different seeds.
        assert_ne!(s1, s2);
    }

    #[test]
    fn parse_tun_net_accepts_and_rejects() {
        assert_eq!(parse_tun_net("10.99.0").unwrap(), [10, 99, 0]);
        assert_eq!(parse_tun_net("192.168.7").unwrap(), [192, 168, 7]);
        assert!(parse_tun_net("10.99.0.1").is_err()); // 4 octets
        assert!(parse_tun_net("10.99").is_err()); // 2 octets
        assert!(parse_tun_net("10.999.0").is_err()); // out of range
    }
}
